[package]
name = "x30"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
publish = false

[dependencies]
cipher = "=0.5.2"
ctr = "=0.10.1"
idea = "=0.6.0"
hmac = "=0.13.0"
sha2_011 = { package = "sha2", version = "=0.11.0" }
getrandom = "=0.4.3"
pbkdf2 = "=0.12.2"
sha2 = "=0.10.9"
rpassword = "=7.5.4"
tempfile = "=3.27.0"

[lints.rust]
unsafe_code = "forbid"